FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

# npm install を毎回やり直さなくて済む
COPY frontend/package*.json ./
RUN npm install

COPY frontend .

EXPOSE 3000

CMD ["npm", "run", "dev"]